- Save restore tgt dir to ini file. - Use values from ini files instead of cmdline parameters.

diff --git a/restore/verify_restore b/restore/verify_restore
--- a/restore/verify_restore
+++ b/restore/verify_restore
@@ -1,38 +1,69 @@
 #!/usr/bin/bash
 
-set -x
+function die() {
+    echo "ERROR: $*"
+    exit 99
+}
 
-#Original source snapshot
-# get this from
-# grep 'fs-root' /gpfs/fs0/DR/INFO/HOME/TIMESTAMP/*.dcf
-FSROOT=/gpfs/fs0/home/.snapshots/home_20170519_0200
+function dumpvars() {
+    for vname; do
+        echo "$vname => '${!vname}'"
+    done
+}
 
-#Where to extract dar files
-RESTOREROOT=/gpfs/fs0/RESTORETESTTGT
+PGM=$( basename $0 )
+INFODIR=$( dirname $0 )
+source $INFODIR/read_ini.sh
 
-#Where are the DAR files
-DOWNLOAD_DIR=/gpfs/fs0/DR/RESTORETESTSRC
+PARALLEL=$( which parallel )
+[[ -z "$PARALLEL" ]] && die "Unable to find 'parallel'"
+[[ -x "$PARALLEL" ]] || die "Parallel program, 'parallel', is not executable"
 
-# Verify DAR to SOURCE
+# Get Original Source
+first_dar_ini=$( ls "$INFODIR"/*0001.ini )
+[[ -f "$first_dar_ini" ]] || die "Can't find first dar ini file"
+read_ini "$first_dar_ini" -p SRC
+[[ -z "${SRC__FS_ROOT}" ]] && die "Cound not find FS_ROOT in ini file '$first_dar_ini'"
+[[ -d "${SRC__FS_ROOT}" ]] || die "FS_ROOT '${SRC__FS_ROOT}' is not a valid directory"
 
-#single-threaded
-#RSYNCOUT="$DOWNLOAD_DIR/rsync_compare.out"
-#rsync -n -avHAXi $FSROOT/ $RESTOREROOT/ >"$RSYNCOUT"
-#diffcount=$( wc -l "$RSYNCOUT" | cut -d ' ' -f1 )
-#[[ $diffcount -gt 5 ]] && { echo "Differences found: see file '$RSYNCOUT'"
-#} || { echo "No differences found!"
-#}
+# Get Restore Root
+fn_restore_ini=$( ls "$INFODIR"/restore.ini )
+[[ -f "$fn_restore_ini" ]] || dir "Can't find restore.ini file"
+read_ini "$fn_restore_ini" -p TGT
+[[ -z "${TGT__RESTORE__ROOT}" ]] && die "Could not find RESTORE ROOT in ini file '$fn_restore_ini'"
+[[ -d "${TGT__RESTORE__ROOT}" ]] || die "RESTORE ROOT '${TGT__RESTORE__ROOT}' is not a valid directory"
 
-#parallel
-rsync_opts='-nilptgoHAX'
-#RSYNCLOGBASE="$DOWNLOAD_DIR/rsync_compare.out"
-RSYNCLOGBASE="/root/rsync_compare.out"
+RSYNCLOGBASE="$INFODIR/rsync_compare.out"
+
+dumpvars SRC__FS_ROOT TGT__RESTORE__ROOT INFODIR RSYNCLOGBASE
+
+echo "Continue?"
+select yn in Yes No; do
+    case $yn in
+        Yes ) break;;
+          * ) exit;;
+    esac
+done
+
+### Compare source to restored
 # clean up any existing rsync log files
 rm ${RSYNCLOGBASE}*
-# compare top level
-find "$FSROOT" -mindepth 1 -maxdepth 1 -print0 \
-| parallel -0 -j1 "rsync $rsync_opts $FSROOT/{} $RESTOREROOT/{} >>${RSYNCLOGBASE}.."
-# compare each element in first sub level below top
-rsync_opts='-niaHAX'
-find "$FSROOT/" -mindepth 1 -maxdepth 1 -type d -name 'aloftus' -printf "%f\0" \
-| parallel -0 -j16 "rsync $rsync_opts $FSROOT/{}/ $RESTOREROOT/{}/ >${RSYNCLOGBASE}.{}"
+
+#single-threaded
+set -x
+rsync -navHAXi ${SRC__FS_ROOT}/ ${TGT__RESTORE__ROOT}/ >"$RSYNCLOGBASE"
+set +x
+diffcount=$( wc -l "$RSYNCLOGBASE" | cut -d ' ' -f1 )
+[[ $diffcount -gt 5 ]] && { echo "Differences found: see file '$RSYNCLOGBASE'"
+} || { echo "No differences found!"
+}
+
+##parallel
+#rsync_opts='-nilptgoHAX'
+##### compare top level
+####find "${SRC__FS_ROOT}" -mindepth 1 -maxdepth 1 -print0 \
+####| parallel -0 -j1 "rsync $rsync_opts ${SRC__FS_ROOT}/{} ${TGT__RESTORE__ROOT}/{} >>${RSYNCLOGBASE}.."
+## compare each element in first sub level below top
+#rsync_opts='-niaHAX'
+#find "${SRC__FS_ROOT}/" -mindepth 1 -maxdepth 1 -type d -name 'aloftus' -printf "%f\0" \
+#| parallel -0 -j16 "rsync $rsync_opts ${SRC__FS_ROOT}/{}/ ${TGT__RESTORE__ROOT}/{}/ >${RSYNCLOGBASE}.{}"
diff --git a/restore/xtract_dar b/restore/xtract_dar
--- a/restore/xtract_dar
+++ b/restore/xtract_dar
@@ -2,48 +2,76 @@
 
 set -x
 
-DAR=/gpfs/fs0/DR/bin/dar_static
-PARALLEL=/usr/local/bin/parallel
+PGM=$( basename $0 )
+BASE=$( dirname $0 )
 
-#Original source snapshot
-# get this from
-# grep 'fs-root' /gpfs/fs0/DR/INFO/HOME/TIMESTAMP/*.dcf
-FSROOT=/gpfs/fs0/home/.snapshots/home_20170524_0200
+source $BASE/funcs.sh
+source $BASE/read_ini.sh
+source $BASE/crudini
+
+PARALLEL=$( which parallel )
+[[ -z "$PARALLEL" ]] && die "Unable to find 'parallel'"
+[[ -x "$PARALLEL" ]] || die "Parallel program, 'parallel', is not executable"
+
+DAR=$( which dar )
+[[ -z "$DAR" ]] && DAR=$BASE/dar
+[[ -z "$DAR" ]] && die "Unable to find 'dar' program"
+[[ -x "$DAR" ]] || die "Dar binary '$DAR' is not executable"
+
+#DAR_OPTS=( --no-warn=all -Q --verbose=all --overwriting-policy Oo )
+DAR_OPTS=( --no-warn=all -Q --verbose=all --overwriting-policy Pp )
 
 #Where to extract dar files
 RESTOREROOT=/gpfs/fs0/RESTORETESTTGT
+if [[ $# -lt 1 ]] ; then
+    echo "No restore path specified. Using default value: $RESTOREROOT"
+    select yn in Yes No; do
+        case $yn in
+            Yes ) break;;
+            * ) exit;;
+        esac
+    done
+fi
 
-#Where are the DAR files
-DOWNLOAD_DIR=/gpfs/fs0/DR/RESTORETESTSRC
-
-DAR_OPTS=( --no-warn=all -Q --verbose=all --overwriting-policy Oo )
-#DAR_OPTS=( --no-warn=all -Q --verbose=all --overwriting-policy Pp )
-
-# Clean destination directory
+# Check for clean restore directory
+tgtsize=$( find "$RESTOREROOT" -maxdepth 1 | wc -l )
+if [[ $tgtsize -gt 1 ]] ; then
+    echo "Restore directory is not empty. Purge contents of restore directory?"
+    select yn in Yes No; do
+        case $yn in
+            Yes ) break;;
+            * ) exit;;
+        esac
+    done
+fi
 find "$RESTOREROOT" -delete
-mkdir "$RESTOREROOT" || { 
-    echo "Error creating restore dir '$RESTOREROOT'"
-    exit 1
-}
-# Clean output directory
-find $DOWNLOAD_DIR -mindepth 1 ! -name '*.dar' -delete
+mkdir "$RESTOREROOT" || die "Error creating restore dir '$RESTOREROOT'"
+crudini --set restore.ini RESTORE ROOT "$RESTOREROOT"
+
+# Get fsroot
+FSROOT=$( grep FS_ROOT $BASE/*.ini | head -1 | awk '{print $NF}' )
+[[ -d "$FSROOT" ]] || die "No dir found for FSROOT='$FSROOT'"
+
+
+## Clean output directory
+rm -f $BASE/*.restore.{log,err,cmd,cmd.log,queue,sqlworker.cmd}
 
 
 # Create cmd files for each dar extraction (so they can be run in parallel)
-alldars=( $( find $DOWNLOAD_DIR -name '*.dar.1.dar' ) )
+alldars=( $( find $BASE -name '*.dar.1.dar' ) )
 for darfile in "${alldars[@]}"; do
     fnbase=$( basename $darfile '.dar.1.dar' )
-    darfilebase=$DOWNLOAD_DIR/${fnbase}.dar
-    logfile=${darfilebase}.restore.log
-    errfile=${darfilebase}.restore.err
-    cmdfile=${darfilebase}.restore.cmd
+    darbase=$BASE/${fnbase}.dar
+    logfile=${darbase}.restore.log
+    errfile=${darbase}.restore.err
+    cmdfile=${darbase}.restore.cmd
     outfile=${cmdfile}.log
     cat <<ENDHERE >$cmdfile
 #!/bin/bash
 start=\$( date '+%s' )
 echo "STARTTIME: \$start" > $outfile
 $DAR ${DAR_OPTS[@]} \\
---extract $darfilebase \\
+--extract $darbase \\
 --fs-root $RESTOREROOT \\
 1> $logfile \\
 2> $errfile
@@ -55,15 +83,15 @@ ENDHERE
 done
 
 # Create sqlmaster task queue
-Qfile=$DOWNLOAD_DIR/joblog.queue
+Qfile=$BASE/restore.queue
 sqlfile=$( echo $Qfile | sed -e 's/\//%2F/g' )
 dburl="sqlite3:///$sqlfile/tasks"
-find $DOWNLOAD_DIR -name '*.cmd' \
+find $BASE -name '*restore.cmd' \
 | $PARALLEL --sqlmaster $dburl bash {}
 
 
 # Create sqlworker cmd script
-sqlworker_cmdfile=$DOWNLOAD_DIR/sqlworker.cmd
+sqlworker_cmdfile=$BASE/restore.sqlworker.cmd
 cat <<ENDHERE >$sqlworker_cmdfile
 #!/bin/bash
 # Dont continue if active parallel or dar processes
